### ISSUE TITLE
Note required PHP libraries in README

### ISSUE THREAD

**Issue by pjohanneson** [chnm/anthologize#112]
I had to install `php-mbstring` (and probably `php-tcpdf`) in order to make this plugin work in a local LAMP server. I think it would be a good idea to indicate what non-default PHP libraries (as `mbstring` is, [per the PHP docs](https://www.php.net/manual/en/mbstring.installation.php)) are required to make Anthologize fully functional.

**Comment by boonebgorges** [comment]
Thanks! This is a good idea.

**Comment by boonebgorges** [comment]
Added a few notes in https://github.com/chnm/anthologize/commit/ab984c003a2ace922d87f1e7f29d78110f401804
