### ISSUE TITLE
Filter out draft posts

### ISSUE THREAD

**Issue by mnelson4** [chnm/anthologize#98]
I just used this to create a PDF from my site and it worked great. Thanks!
One oddity though: all my draft posts were included in the "items" area on the left (when viewing a project). That might be what some folks want, but I'm guessing usually not. (It's also possible some folks might want to exclude protected/private posts).
So I'm thinking it would be nice if you could, in addition to the current filters, filter the posts by status.
(FYI I'm willing to put some legwork into making this happen, just first wanting to get some thought on how feasible this is).

**Comment by boonebgorges** [comment]
Yup, this was likely an oversight in the initial implementation. Feel free to work something up if you would like!

**Comment by mnelson4** [comment]
kk. Do you think we should just always exclude draft posts? Or should it be optional?

**Comment by boonebgorges** [comment]
Fixed by #101
